apiVersion: 1

datasources:
  - name: Loki
    uid: loki-sign-language
    type: loki
    access: proxy
    url: http://127.0.0.1:3100
    isDefault: true
    editable: false
    jsonData:
      maxLines: 1000
      timeout: 60

  - name: Prometheus
    uid: prometheus-sign-language
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
