"""
Константы приложения.
"""
# Размерность embeddings (RuBERT base)
EMBEDDING_DIMENSION = 768

# Максимальная длина полей
MAX_WORD_LENGTH = 200
MAX_CATEGORY_NAME_LENGTH = 200
MAX_CATEGORY_ID_LENGTH = 50
MAX_DESCRIPTION_LENGTH = 1000
MAX_CONTEXT_DESCRIPTION_LENGTH = 500

# Размеры файлов (в байтах)
VIDEO_MAX_SIZE = 50 * 1024 * 1024  # 50 MB

# Параметры токенизации
TOKENIZER_MAX_LENGTH = 512

# Пагинация
DEFAULT_PAGE = 1
DEFAULT_PER_PAGE = 50
MAX_PER_PAGE = 100

# Коды ошибок API
ERROR_CODES = {
    'INVALID_REQUEST': 'INVALID_REQUEST',
    'MISSING_CREDENTIALS': 'MISSING_CREDENTIALS',
    'INVALID_CREDENTIALS': 'INVALID_CREDENTIALS',
    'TOKEN_REQUIRED': 'TOKEN_REQUIRED',
    'TOKEN_EXPIRED': 'TOKEN_EXPIRED',
    'INVALID_TOKEN': 'INVALID_TOKEN',
    'INVALID_TOKEN_FORMAT': 'INVALID_TOKEN_FORMAT',
    'USER_NOT_FOUND': 'USER_NOT_FOUND',
    'VALIDATION_ERROR': 'VALIDATION_ERROR',
    'NOT_FOUND': 'NOT_FOUND',
    'DUPLICATE_ID': 'DUPLICATE_ID',
    'CATEGORY_NOT_FOUND': 'CATEGORY_NOT_FOUND',
    'CATEGORY_HAS_SIGNS': 'CATEGORY_HAS_SIGNS',
    'NO_FILE': 'NO_FILE',
    'INVALID_FORMAT': 'INVALID_FORMAT',
    'FILE_TOO_LARGE': 'FILE_TOO_LARGE',
    'SIGN_NOT_FOUND': 'SIGN_NOT_FOUND',
    'INVALID_SYNONYM': 'INVALID_SYNONYM',
    'SYNONYM_EXISTS': 'SYNONYM_EXISTS',
    'SYNONYM_NOT_FOUND': 'SYNONYM_NOT_FOUND',
    'MODEL_NOT_AVAILABLE': 'MODEL_NOT_AVAILABLE',
    'INVALID_EMBEDDINGS': 'INVALID_EMBEDDINGS',
    'GENERATION_FAILED': 'GENERATION_FAILED',
    'INTERNAL_ERROR': 'INTERNAL_ERROR',
    'MISSING_FIELD': 'MISSING_FIELD',
}

